
import random

# Define rules and responses
rules = {
    'hi': ['hello', 'hey', 'hi there!'],
    'how are you': ['I am good, thank you!', 'I am functioning optimally.', 'All systems operational.'],
    'what is your name': ['I am a chatbot.', 'Call me ChatBot.', 'You can call me ChatMaster.'],
    # 'tell me a joke': [
    #     'Why did the scarecrow win an award? Because he was outstanding in his field!',
    #     'Parallel lines have so much in common. It\'s a shame they\'ll never meet.',
    #     'I told my wife she was drawing her eyebrows too high. She looked surprised!'
    # ],
    # 'who are you': [
    #     'I am ChatBot, your friendly AI companion!',
    #     'You can call me AssistantBot, here to help you.'
    # ],
    # 'thank you': ['You\'re welcome!', 'No problem.', 'Happy to help!'],
    # 'tell me a story': [
    #     'Once upon a time, in a land far, far away...',
    #     'There once was a brave knight who set out on a quest...'
    # ],
    'what is your favorite color': ['I think I would like the color blue.', 'I like all colors equally.'],
    'who is your favorite superhero': ['I admire Iron Man.'],
    'how old are you': ['I don\'t have an age. I am here to assist you.'],
    'what is the meaning of life': ['The meaning of life is a complex philosophical question.'],
    'give me a book recommendation': ['I recommend "The Hitchhiker\'s Guide to the Galaxy" by Douglas Adams.'],
    'what is the weather like today': ['I\'m sorry, I don\'t have real-time data access at the moment.'],
    'what is the capital of France': ['The capital of France is Paris.'],
    'what is the tallest mountain in the world': ['Mount Everest is the tallest mountain in the world.'],
    'what is the largest ocean': ['The Pacific Ocean is the largest ocean in the world.'],
    'what is the capital of Japan': ['The capital of Japan is Tokyo.'],
    'how far is the moon': ['The average distance from the Earth to the Moon is about 238,855 miles (384,400 kilometers).'],
    'who painted the Mona Lisa': ['The Mona Lisa was painted by Leonardo da Vinci.'],
    'what is the square root of 16': ['The square root of 16 is 4.'],
    'tell me a riddle': ['I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I? (Answer: An echo)'],
    'what is the largest planet in our solar system': ['Jupiter is the largest planet in our solar system.'],
    'who wrote Romeo and Juliet': ['Romeo and Juliet was written by William Shakespeare.'],
    'tell me a fun fact': ['Did you know that honey never spoils? Archaeologists have discovered pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly good to eat!'],
    'what is the tallest building in the world': ['The tallest building in the world is the Burj Khalifa in Dubai, UAE.'],
    'who was the first person to step on the moon': ['Neil Armstrong was the first person to step on the moon during NASA\'s Apollo 11 mission in 1969.'],
    'tell me a science fact': ['The Earth is not a perfect sphere; it is an oblate spheroid due to its rotation.'],
    'what is the Pythagorean theorem': ['The Pythagorean theorem states that in a right triangle, the square of the length of the hypotenuse (the side opposite the right angle) is equal to the sum of the squares of the other two sides.'],
    'who is the author of "Pride and Prejudice"': ['The author of "Pride and Prejudice" is Jane Austen.'],
    'how many continents are there': ['There are seven continents on Earth: Africa, Antarctica, Asia, Europe, North America, Australia (Oceania), and South America.'],
    'tell me a famous quote': ['"The only way to do great work is to love what you do." - Steve Jobs'],
    'what is the chemical symbol for gold': ['The chemical symbol for gold is Au (from the Latin "aurum").'],
    'who painted "Starry Night"': ['"Starry Night" was painted by Vincent van Gogh.'],
    'tell me a programming joke': ['Why don\'t programmers like nature? It has too many bugs.'],
    'what is the world\'s largest desert': ['The world\'s largest desert is the Antarctic Desert.'],
    'who discovered electricity': ['Electricity wasn\'t discovered by a single person, but key contributions were made by Benjamin Franklin, Michael Faraday, and Thomas Edison.'],
    'tell me an interesting historical fact': ['In ancient Rome, they used urine to clean their clothes because the ammonia in urine acted as a cleaning agent.'],
    'what is the national flower of Japan': ['The national flower of Japan is the cherry blossom, known as "sakura."'],
    'who wrote "The Great Gatsby"': ['"The Great Gatsby" was written by F. Scott Fitzgerald.'],
    'tell me a fun animal fact': ['Penguins have an organ above their eyes that converts seawater to fresh water, allowing them to survive in saltwater environments.'],
    'what is the capital of Brazil': ['The capital of Brazil is Brasília.'],
    'who is the first woman in space': ['The first woman in space was Valentina Tereshkova, a Soviet cosmonaut.'],
    'tell me a famous movie quote': ['"May the Force be with you." - Star Wars'],
    'what is the chemical symbol for oxygen': ['The chemical symbol for oxygen is O.'],
    'who painted the ceiling of the Sistine Chapel': ['The ceiling of the Sistine Chapel was painted by Michelangelo.'],
    'tell me a technology fact': ['The first computer bug was a real insect! In 1947, a moth caused a computer malfunction, and it was taped into a logbook as the "first actual case of a bug."'],
    'what is the world\'s longest river': ['The world\'s longest river is the Nile, in Africa.'],
    'who is the author of "To Kill a Mockingbird"': ['The author of "To Kill a Mockingbird" is Harper Lee.'],
    'tell me a space fact': ['There are more stars in the universe than there are grains of sand on all the beaches on Earth.'],
    'what is the chemical symbol for carbon': ['The chemical symbol for carbon is C.'],
    'who is the artist of the Mona Lisa': ['The artist of the Mona Lisa is Leonardo da Vinci.'],
    'tell me a cooking tip': ['To prevent tears while chopping onions, chill the onion in the refrigerator for about 30 minutes before cutting.'],
    'what is the currency of Japan': ['The currency of Japan is the Japanese Yen (JPY).'],
    'who was the first American astronaut in space': ['The first American astronaut in space was Alan Shepard.'],
    'tell me an interesting fact about the human body': ['The human brain has the capacity to generate approximately 20 watts of electrical power.'],
    'what is the national bird of the United States': ['The national bird of the United States is the Bald Eagle.'],
    'who wrote "1984"': ['"1984" was written by George Orwell.'],
    'tell me a geography fact': ['The lowest point on Earth is the Challenger Deep in the Mariana Trench, about 36,070 feet (10,994 meters) deep.'],
    'what is the chemical symbol for hydrogen': ['The chemical symbol for hydrogen is H.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a sports fact': ['The fastest recorded tennis serve was 163.7 mph (263.4 km/h) by Sam Groth.'],
    'what is the world\'s largest mammal': ['The world\'s largest mammal is the blue whale.'],
    'who is the author of "The Catcher in the Rye"': ['The author of "The Catcher in the Rye" is J.D. Salinger.'],
    'tell me a famous historical speech': ['"I have a dream." - Martin Luther King Jr.'],
    'what is the chemical symbol for silver': ['The chemical symbol for silver is Ag (from the Latin "argentum").'],
    'who is the artist of "The Starry Night"': ['"The Starry Night" was painted by Vincent van Gogh.'],
    'tell me a computer science fact': ['The first computer programmer was Ada Lovelace, who wrote the first algorithm intended to be processed by a machine in the mid-1800s.'],
    'what is the world\'s largest volcano': ['Mauna Loa in Hawaii is the world\'s largest volcano by volume.'],
    'who wrote "Brave New World"': ['"Brave New World" was written by Aldous Huxley.'],
    'tell me a psychology fact': ['Phobophobia is the fear of having a phobia.'],
    'what is the tallest tree in the world': ['The tallest tree in the world is Hyperion, a coast redwood (Sequoia sempervirens) in California, USA.'],
    'who is the first man to walk on the moon': ['The first man to walk on the moon was Neil Armstrong during NASA\'s Apollo 11 mission in 1969.'],
    'tell me a famous art quote': ['"Every artist was first an amateur." - Ralph Waldo Emerson'],
    'what is the chemical symbol for calcium': ['The chemical symbol for calcium is Ca.'],
    'who painted "Guernica"': ['"Guernica" was painted by Pablo Picasso.'],
    'tell me a music fact': ['The shortest song ever recorded is "You Suffer" by the band Napalm Death, lasting just 1.316 seconds.'],
    'what is the world\'s largest lake': ['The world\'s largest lake by surface area is the Caspian Sea.'],
    'who is the author of "Lord of the Flies"': ['The author of "Lord of the Flies" is William Golding.'],
    'tell me a famous space quote': ['"That\'s one small step for man, one giant leap for mankind." - Neil Armstrong'],
    'what is the chemical symbol for nitrogen': ['The chemical symbol for nitrogen is N.'],
    'who painted "American Gothic"': ['"American Gothic" was painted by Grant Wood.'],
    'tell me a science fiction fact': ['The term "robot" was first coined by Czech playwright Karel Čapek in his 1920 play "R.U.R." (Rossum\'s Universal Robots).'],
    'what is the world\'s smallest country': ['The world\'s smallest country by land area is Vatican City.'],
    'who is the author of "Moby Dick"': ['The author of "Moby Dick" is Herman Melville.'],
    'tell me a famous literature quote': ['"The only way to deal with fear is to face it head on." - Stephen King'],
    'what is the chemical symbol for sodium': ['The chemical symbol for sodium is Na (from the Latin "natrium").'],
    'who painted "Girl with a Pearl Earring"': ['"Girl with a Pearl Earring" was painted by Johannes Vermeer.'],
    'tell me a fun fact about the ocean': ['The ocean contains an estimated 20 million tons of gold dissolved in its waters, but in such low concentrations that it\'s not feasible to extract it.'],
    'what is the national flower of England': ['The national flower of England is the Tudor Rose.'],
    'who was the first woman to fly solo across the Atlantic': ['The first woman to fly solo across the Atlantic Ocean was Amelia Earhart.'],
    'tell me a famous historical quote': ['"We hold these truths to be self-evident, that all men are created equal." - Declaration of Independence'],
    'what is the chemical symbol for potassium': ['The chemical symbol for potassium is K.'],
    'who painted "The Last Supper"': ['"The Last Supper" was painted by Leonardo da Vinci.'],
    'tell me a fun fact about space': ['A day on Venus is longer than its year. Venus takes about 243 Earth days to rotate on its axis but only about 225 Earth days to orbit the Sun.'],
    'what is the national flower of India': ['The national flower of India is the lotus.'],
    'who is the first woman to win a Nobel Prize': ['The first woman to win a Nobel Prize was Marie Curie, who won the Nobel Prize in Physics in 1903.'],
    'tell me a famous movie line': ['"There\'s no place like home." - The Wizard of Oz'],
    'what is the chemical symbol for iron': ['The chemical symbol for iron is Fe (from the Latin "ferrum").'],
    'who painted "Water Lilies"': ['"Water Lilies" was painted by Claude Monet.'],
    'tell me a technology fact': ['The first computer mouse was invented by Doug Engelbart in 1964, and it was made of wood.'],
    'what is the world\'s smallest ocean': ['The world\'s smallest ocean is the Arctic Ocean.'],
    'who is the author of "The Odyssey"': ['The author of "The Odyssey" is Homer.'],
    'tell me a famous psychology quote': ['"The greatest glory in living lies not in never falling, but in rising every time we fall." - Nelson Mandela'],
    'what is the chemical symbol for copper': ['The chemical symbol for copper is Cu (from the Latin "cuprum").'],
    'who painted "The Birth of Venus"': ['"The Birth of Venus" was painted by Sandro Botticelli.'],
    'tell me a sports fact': ['The first Olympic Games were held in Olympia, Greece, in 776 BC.'],
    'what is the world\'s largest island': ['The world\'s largest island is Greenland.'],
    'who is the author of "Percy Jackson and the Olympians"': ['The author of "Percy Jackson and the Olympians" is Rick Riordan.'],
    'tell me a famous music quote': ['"Without music, life would be a mistake." - Friedrich Nietzsche'],
    'what is the chemical symbol for mercury': ['The chemical symbol for mercury is Hg (from the Latin "hydrargyrum").'],
    'who painted "Venus de Milo"': ['"Venus de Milo" is believed to have been sculpted by Alexandros of Antioch.'],
    'tell me a fun fact about the human brain': ['The human brain can process information as fast as 120 meters per second.'],
    'what is the national animal of China': ['The national animal of China is the giant panda.'],
    'who is the first man to fly': ['The first man to fly was Orville Wright during a powered flight in 1903.'],
    'tell me a famous art quote': ['"Every artist dips his brush in his own soul, and paints his own nature into his pictures." - Henry Ward Beecher'],
    'what is the chemical symbol for phosphorus': ['The chemical symbol for phosphorus is P.'],
    'who painted "Nighthawks"': ['"Nighthawks" was painted by Edward Hopper.'],
    'tell me a science fiction fact': ['The word "robot" comes from the Czech word "robota," meaning "forced labor" or "drudgery."'],
    'what is the world\'s largest desert by area': ['The world\'s largest desert by area is the Sahara Desert.'],
    'who is the author of "Frankenstein"': ['The author of "Frankenstein" is Mary Shelley.'],
    'tell me a famous quote about success': ['"Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill'],
    'what is the chemical symbol for sulfur': ['The chemical symbol for sulfur is S.'],
    'who painted "The Girl with the Red Hat"': ['"The Girl with the Red Hat" was painted by Johannes Vermeer.'],
    'tell me a cooking fact': ['Adding a pinch of salt to your coffee can help reduce its bitterness.'],
    'what is the national animal of the United States': ['The national animal of the United States is the bald eagle.'],
    'who was the first woman to fly solo across the Atlantic': ['The first woman to fly solo across the Atlantic Ocean was Amelia Earhart in 1932.'],
    'tell me a famous history quote': ['"The only thing we learn from history is that we learn nothing from history." - Friedrich Hegel'],
    'what is the chemical symbol for tin': ['The chemical symbol for tin is Sn (from the Latin "stannum").'],
    'who painted "Whistler\'s Mother"': ['"Whistler\'s Mother" was painted by James McNeill Whistler.'],
    'tell me a fun fact about animals': ['A group of flamingos is called a "flamboyance."'],
    'what is the national flower of France': ['The national flower of France is the fleur-de-lis.'],
    'who is the first human in space': ['The first human in space was Yuri Gagarin, a Soviet cosmonaut.'],
    'tell me a famous astronomy quote': ['"The important achievement of Apollo was demonstrating that humanity is not forever chained to this planet and our visions go rather further than that and our opportunities are unlimited." - Neil Armstrong'],
    'what is the chemical symbol for lead': ['The chemical symbol for lead is Pb (from the Latin "plumbum").'],
    'who painted "The Kiss"': ['"The Kiss" was painted by Gustav Klimt.'],
    'tell me a technology fact': ['The first email was sent in 1971 by Ray Tomlinson.'],
    'what is the world\'s largest flower': ['The world\'s largest flower is the Rafflesia arnoldii.'],
    'who is the author of "The Iliad"': ['The author of "The Iliad" is Homer.'],
    'tell me a famous psychology quote': ['"In the middle of every difficulty lies opportunity." - Albert Einstein'],
    'what is the chemical symbol for zinc': ['The chemical symbol for zinc is Zn.'],
    'who painted "The Scream"': ['"The Scream" was painted by Edvard Munch.'],
    'tell me a fun fact about the heart': ['The heart pumps about 2,000 gallons (7,570 liters) of blood through the body every day.'],
    'what is the national animal of Australia': ['The national animal of Australia is the red kangaroo.'],
    'who was the first American woman in space': ['The first American woman in space was Sally Ride.'],
    'tell me a famous science quote': ['"Science knows no country, because knowledge belongs to humanity, and is the torch which illuminates the world." - Louis Pasteur'],
    'what is the chemical symbol for gold': ['The chemical symbol for gold is Au (from the Latin "aurum").'],
    'who painted "Las Meninas"': ['"Las Meninas" was painted by Diego Velázquez.'],
    'tell me a sports fact': ['Basketball was invented in 1891 by Dr. James Naismith, a Canadian physical education instructor.'],
    'what is the world\'s smallest bird': ['The world\'s smallest bird is the bee hummingbird.'],
    'who is the author of "The Picture of Dorian Gray"': ['The author of "The Picture of Dorian Gray" is Oscar Wilde.'],
    'tell me a famous music quote': ['"Music can change the world because it can change people." - Bono'],
    'what is the chemical symbol for silver': ['The chemical symbol for silver is Ag (from the Latin "argentum").'],
    'who painted "Liberty Leading the People"': ['"Liberty Leading the People" was painted by Eugène Delacroix.'],
    'tell me a fun fact about insects': ['Fleas can jump up to 350 times their body length.'],
    'what is the national animal of Canada': ['The national animal of Canada is the beaver.'],
    'who was the first woman to win the Nobel Prize': ['The first woman to win a Nobel Prize was Marie Curie, who won the Nobel Prize in Physics in 1903 and in Chemistry in 1911.'],
    'tell me a famous history quote': ['"Those who cannot remember the past are condemned to repeat it." - George Santayana'],
    'what is the chemical symbol for helium': ['The chemical symbol for helium is He.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a fun fact about the human body': ['The human nose can remember about 50,000 different scents.'],
    'what is the national animal of Russia': ['The national animal of Russia is the Russian bear.'],
    'who is the first human to reach the North Pole': ['The first human to reach the North Pole was Robert Peary.'],
    'tell me a famous art quote': ['"Art is the most intense mode of individualism that the world has known." - Oscar Wilde'],
    'what is the chemical symbol for neon': ['The chemical symbol for neon is Ne.'],
    'who painted "The Birth of Adam"': ['"The Birth of Adam" is part of Michelangelo\'s frescoes on the ceiling of the Sistine Chapel.'],
    'tell me a science fiction fact': ['The first science fiction novel is often considered to be "Frankenstein" by Mary Shelley, published in 1818.'],
    'what is the world\'s largest island by area': ['The world\'s largest island by area is Greenland.'],
    'who is the author of "War and Peace"': ['The author of "War and Peace" is Leo Tolstoy.'],
    'tell me a famous quote about love': ['"The greatest thing you\'ll ever learn is just to love and be loved in return." - Nat King Cole'],
    'what is the chemical symbol for chlorine': ['The chemical symbol for chlorine is Cl.'],
    'who painted "A Sunday Afternoon on the Island of La Grande Jatte"': ['"A Sunday Afternoon on the Island of La Grande Jatte" was painted by Georges Seurat.'],
    'tell me a technology fact': ['The first computer, ENIAC, weighed more than 27 tons and took up 1,800 square feet of space.'],
    'what is the world\'s largest canyon': ['The world\'s largest canyon is the Grand Canyon in the United States.'],
    'who is the author of "Wuthering Heights"': ['The author of "Wuthering Heights" is Emily Brontë.'],
    'tell me a famous psychology quote': ['"What we achieve inwardly will change outer reality." - Plutarch'],
    'what is the chemical symbol for potassium': ['The chemical symbol for potassium is K.'],
    'who painted "The School of Athens"': ['"The School of Athens" was painted by Raphael.'],
    'tell me a fun fact about birds': ['Hummingbirds are the only birds that can fly backwards.'],
    'what is the national animal of South Africa': ['The national animal of South Africa is the springbok.'],
    'who was the first person to fly across the Atlantic solo': ['The first person to fly across the Atlantic solo was Charles Lindbergh.'],
    'tell me a famous science quote': ['"Science is a way of thinking much more than it is a body of knowledge." - Carl Sagan'],
    'what is the chemical symbol for argon': ['The chemical symbol for argon is Ar.'],
    'who painted "The Night Watch"': ['"The Night Watch" was painted by Rembrandt van Rijn.'],
    'tell me a fun fact about the brain': ['The brain generates about 20 watts of electrical power, enough to power a dim light bulb.'],
    'what is the national bird of Australia': ['The national bird of Australia is the emu.'],
    'who is the first person to reach the South Pole': ['The first person to reach the South Pole was Roald Amundsen.'],
    'tell me a famous astronomy quote': ['"The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself." - Carl Sagan'],
    'what is the chemical symbol for titanium': ['The chemical symbol for titanium is Ti.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a fun fact about the human body': ['The human eye can distinguish about 10 million different colors.'],
    'what is the national animal of Japan': ['The national animal of Japan is the green pheasant.'],
    'who was the first woman to fly across the Atlantic solo': ['The first woman to fly across the Atlantic solo was Amelia Earhart in 1932.'],
    'tell me a famous history quote': ['"History is a set of lies agreed upon." - Napoleon Bonaparte'],
    'what is the chemical symbol for barium': ['The chemical symbol for barium is Ba.'],
    'who painted "The Garden of Earthly Delights"': ['"The Garden of Earthly Delights" was painted by Hieronymus Bosch.'],
    'tell me a fun fact about plants': ['Bamboo is one of the fastest-growing plants and can grow up to 3 feet in a single day.'],
    'what is the national animal of China': ['The national animal of China is the giant panda.'],
    'who was the first man to fly across the Atlantic solo non-stop': ['The first man to fly across the Atlantic solo non-stop was Charles Lindbergh in 1927.'],
    'tell me a famous science quote': ['"Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less." - Marie Curie'],
    'what is the chemical symbol for aluminum': ['The chemical symbol for aluminum is Al.'],
    'who painted "The Birth of Venus"': ['"The Birth of Venus" was painted by Sandro Botticelli.'],
    'tell me a fun fact about the heart': ['The heart pumps about 2,000 gallons (7,570 liters) of blood through the body every day.'],
    'what is the national animal of Russia': ['The national animal of Russia is the Russian bear.'],
    'who is the first human to reach the North Pole': ['The first human to reach the North Pole was Robert Peary.'],
    'tell me a famous art quote': ['"Art is the most intense mode of individualism that the world has known." - Oscar Wilde'],
    'what is the chemical symbol for neon': ['The chemical symbol for neon is Ne.'],
    'who painted "The Birth of Adam"': ['"The Birth of Adam" is part of Michelangelo\'s frescoes on the ceiling of the Sistine Chapel.'],
    'tell me a science fiction fact': ['The first science fiction novel is often considered to be "Frankenstein" by Mary Shelley, published in 1818.'],
    'what is the world\'s largest desert by area': ['The world\'s largest desert by area is the Sahara Desert.'],
    'who is the author of "Frankenstein"': ['The author of "Frankenstein" is Mary Shelley.'],
    'tell me a famous quote about success': ['"Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill'],
    'what is the chemical symbol for sulfur': ['The chemical symbol for sulfur is S.'],
    'who painted "A Sunday Afternoon on the Island of La Grande Jatte"': ['"A Sunday Afternoon on the Island of La Grande Jatte" was painted by Georges Seurat.'],
    'tell me a cooking fact': ['Adding a pinch of salt to your coffee can help reduce its bitterness.'],
    'what is the national animal of the United States': ['The national animal of the United States is the bald eagle.'],
    'who was the first woman to fly solo across the Atlantic': ['The first woman to fly solo across the Atlantic Ocean was Amelia Earhart in 1932.'],
    'tell me a famous history quote': ['"Those who cannot remember the past are condemned to repeat it." - George Santayana'],
    'what is the chemical symbol for tin': ['The chemical symbol for tin is Sn (from the Latin "stannum").'],
    'who painted "Whistler\'s Mother"': ['"Whistler\'s Mother" was painted by James McNeill Whistler.'],
    'tell me a fun fact about insects': ['Fleas can jump up to 350 times their body length.'],
    'what is the national animal of France': ['The national animal of France is the Gallic rooster.'],
    'who is the first person to fly across the Atlantic solo': ['The first person to fly across the Atlantic solo was Charles Lindbergh in 1927.'],
    'tell me a famous science quote': ['"Science is a way of thinking much more than it is a body of knowledge." - Carl Sagan'],
    'what is the chemical symbol for potassium': ['The chemical symbol for potassium is K.'],
    'who painted "The School of Athens"': ['"The School of Athens" was painted by Raphael.'],
    'tell me a fun fact about birds': ['Hummingbirds are the only birds that can fly backwards.'],
    'what is the national animal of Australia': ['The national animal of Australia is the red kangaroo.'],
    'who was the first person to reach the South Pole': ['The first person to reach the South Pole was Roald Amundsen in 1911.'],
    'tell me a famous astronomy quote': ['"The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself." - Carl Sagan'],
    'what is the chemical symbol for titanium': ['The chemical symbol for titanium is Ti.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a fun fact about the human body': ['The human eye can distinguish about 10 million different colors.'],
    'what is the national animal of Japan': ['The national animal of Japan is the green pheasant.'],
    'who was the first woman to fly across the Atlantic solo': ['The first woman to fly across the Atlantic solo was Amelia Earhart in 1932.'],
    'tell me a famous history quote': ['"History is a set of lies agreed upon." - Napoleon Bonaparte'],
    'what is the chemical symbol for barium': ['The chemical symbol for barium is Ba.'],
    'who painted "The Garden of Earthly Delights"': ['"The Garden of Earthly Delights" was painted by Hieronymus Bosch.'],
    'tell me a fun fact about plants': ['Bamboo is one of the fastest-growing plants and can grow up to 3 feet in a single day.'],
    'what is the national animal of China': ['The national animal of China is the giant panda.'],
    'who was the first man to fly across the Atlantic solo non-stop': ['The first man to fly across the Atlantic solo non-stop was Charles Lindbergh in 1927.'],
    'tell me a famous science quote': ['"Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less." - Marie Curie'],
    'what is the chemical symbol for aluminum': ['The chemical symbol for aluminum is Al.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a fun fact about the heart': ['The heart pumps about 2,000 gallons (7,570 liters) of blood through the body every day.'],
    'what is the national animal of Russia': ['The national animal of Russia is the Russian bear.'],
    'who is the first human to reach the North Pole': ['The first human to reach the North Pole was Robert Peary.'],
    'tell me a famous art quote': ['"Art is the most intense mode of individualism that the world has known." - Oscar Wilde'],
    'what is the chemical symbol for neon': ['The chemical symbol for neon is Ne.'],
    'who painted "The Birth of Adam"': ['"The Birth of Adam" is part of Michelangelo\'s frescoes on the ceiling of the Sistine Chapel.'],
    'tell me a science fiction fact': ['The first science fiction novel is often considered to be "Frankenstein" by Mary Shelley, published in 1818.'],
    'what is the world\'s largest desert by area': ['The world\'s largest desert by area is the Sahara Desert.'],
    'who is the author of "Frankenstein"': ['The author of "Frankenstein" is Mary Shelley.'],
    'tell me a famous quote about success': ['"Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill'],
    'what is the chemical symbol for sulfur': ['The chemical symbol for sulfur is S.'],
    'who painted "A Sunday Afternoon on the Island of La Grande Jatte"': ['"A Sunday Afternoon on the Island of La Grande Jatte" was painted by Georges Seurat.'],
    'tell me a cooking fact': ['Adding a pinch of salt to your coffee can help reduce its bitterness.'],
    'what is the national animal of the United States': ['The national animal of the United States is the bald eagle.'],
    'who was the first woman to fly solo across the Atlantic': ['The first woman to fly solo across the Atlantic Ocean was Amelia Earhart in 1932.'],
    'tell me a famous history quote': ['"Those who cannot remember the past are condemned to repeat it." - George Santayana'],
    'what is the chemical symbol for tin': ['The chemical symbol for tin is Sn (from the Latin "stannum").'],
    'who painted "Whistler\'s Mother"': ['"Whistler\'s Mother" was painted by James McNeill Whistler.'],
    'tell me a fun fact about insects': ['Fleas can jump up to 350 times their body length.'],
    'what is the national animal of France': ['The national animal of France is the Gallic rooster.'],
    'who is the first person to fly across the Atlantic solo': ['The first person to fly across the Atlantic solo was Charles Lindbergh in 1927.'],
    'tell me a famous science quote': ['"Science is a way of thinking much more than it is a body of knowledge." - Carl Sagan'],
    'what is the chemical symbol for potassium': ['The chemical symbol for potassium is K.'],
    'who painted "The School of Athens"': ['"The School of Athens" was painted by Raphael.'],
    'tell me a fun fact about birds': ['Hummingbirds are the only birds that can fly backwards.'],
    'what is the national animal of Australia': ['The national animal of Australia is the red kangaroo.'],
    'who was the first person to reach the South Pole': ['The first person to reach the South Pole was Roald Amundsen in 1911.'],
    'tell me a famous astronomy quote': ['"The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself." - Carl Sagan'],
    'what is the chemical symbol for titanium': ['The chemical symbol for titanium is Ti.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a fun fact about the human body': ['The human eye can distinguish about 10 million different colors.'],
    'what is the national animal of Japan': ['The national animal of Japan is the green pheasant.'],
    'who was the first woman to fly across the Atlantic solo': ['The first woman to fly across the Atlantic solo was Amelia Earhart in 1932.'],
    'tell me a famous history quote': ['"History is a set of lies agreed upon." - Napoleon Bonaparte'],
    'what is the chemical symbol for barium': ['The chemical symbol for barium is Ba.'],
    'who painted "The Garden of Earthly Delights"': ['"The Garden of Earthly Delights" was painted by Hieronymus Bosch.'],
    'tell me a fun fact about plants': ['Bamboo is one of the fastest-growing plants and can grow up to 3 feet in a single day.'],
    'what is the national animal of China': ['The national animal of China is the giant panda.'],
    'who was the first man to fly across the Atlantic solo non-stop': ['The first man to fly across the Atlantic solo non-stop was Charles Lindbergh in 1927.'],
    'tell me a famous science quote': ['"Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less." - Marie Curie'],
    'what is the chemical symbol for aluminum': ['The chemical symbol for aluminum is Al.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a fun fact about the heart': ['The heart pumps about 2,000 gallons (7,570 liters) of blood through the body every day.'],
    'what is the national animal of Russia': ['The national animal of Russia is the Russian bear.'],
    'who is the first human to reach the North Pole': ['The first human to reach the North Pole was Robert Peary.'],
    'tell me a famous art quote': ['"Art is the most intense mode of individualism that the world has known." - Oscar Wilde'],
    'what is the chemical symbol for neon': ['The chemical symbol for neon is Ne.'],
    'who painted "The Birth of Adam"': ['"The Birth of Adam" is part of Michelangelo\'s frescoes on the ceiling of the Sistine Chapel.'],
    'tell me a science fiction fact': ['The first science fiction novel is often considered to be "Frankenstein" by Mary Shelley, published in 1818.'],
    'what is the world\'s largest desert by area': ['The world\'s largest desert by area is the Sahara Desert.'],
    'who is the author of "Frankenstein"': ['The author of "Frankenstein" is Mary Shelley.'],
    'tell me a famous quote about success': ['"Success is not final, failure is not fatal: It is the courage to continue that counts." - Winston Churchill'],
    'what is the chemical symbol for sulfur': ['The chemical symbol for sulfur is S.'],
    'who painted "A Sunday Afternoon on the Island of La Grande Jatte"': ['"A Sunday Afternoon on the Island of La Grande Jatte" was painted by Georges Seurat.'],
    'tell me a cooking fact': ['Adding a pinch of salt to your coffee can help reduce its bitterness.'],
    'what is the national animal of the United States': ['The national animal of the United States is the bald eagle.'],
    'who was the first woman to fly solo across the Atlantic': ['The first woman to fly solo across the Atlantic Ocean was Amelia Earhart in 1932.'],
    'tell me a famous history quote': ['"Those who cannot remember the past are condemned to repeat it." - George Santayana'],
    'what is the chemical symbol for tin': ['The chemical symbol for tin is Sn (from the Latin "stannum").'],
    'who painted "Whistler\'s Mother"': ['"Whistler\'s Mother" was painted by James McNeill Whistler.'],
    'tell me a fun fact about insects': ['Fleas can jump up to 350 times their body length.'],
    'what is the national animal of France': ['The national animal of France is the Gallic rooster.'],
    'who is the first person to fly across the Atlantic solo': ['The first person to fly across the Atlantic solo was Charles Lindbergh in 1927.'],
    'tell me a famous science quote': ['"Science is a way of thinking much more than it is a body of knowledge." - Carl Sagan'],
    'what is the chemical symbol for potassium': ['The chemical symbol for potassium is K.'],
    'who painted "The School of Athens"': ['"The School of Athens" was painted by Raphael.'],
    'tell me a fun fact about birds': ['Hummingbirds are the only birds that can fly backwards.'],
    'what is the national animal of Australia': ['The national animal of Australia is the red kangaroo.'],
    'who was the first person to reach the South Pole': ['The first person to reach the South Pole was Roald Amundsen in 1911.'],
    'tell me a famous astronomy quote': ['"The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself." - Carl Sagan'],
    'what is the chemical symbol for titanium': ['The chemical symbol for titanium is Ti.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a fun fact about the human body': ['The human eye can distinguish about 10 million different colors.'],
    'what is the national animal of Japan': ['The national animal of Japan is the green pheasant.'],
    'who was the first woman to fly across the Atlantic solo': ['The first woman to fly across the Atlantic solo was Amelia Earhart in 1932.'],
    'tell me a famous history quote': ['"History is a set of lies agreed upon." - Napoleon Bonaparte'],
    'what is the chemical symbol for barium': ['The chemical symbol for barium is Ba.'],
    'who painted "The Garden of Earthly Delights"': ['"The Garden of Earthly Delights" was painted by Hieronymus Bosch.'],
    'tell me a fun fact about plants': ['Bamboo is one of the fastest-growing plants and can grow up to 3 feet in a single day.'],
    'what is the national animal of China': ['The national animal of China is the giant panda.'],
    'who was the first man to fly across the Atlantic solo non-stop': ['The first man to fly across the Atlantic solo non-stop was Charles Lindbergh in 1927.'],
    'tell me a famous science quote': ['"Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less." - Marie Curie'],
    'what is the chemical symbol for aluminum': ['The chemical symbol for aluminum is Al.'],
    'who painted "The Persistence of Memory"': ['"The Persistence of Memory" was painted by Salvador Dalí.'],
    'tell me a fun fact about the heart': ['The heart pumps about 2,000 gallons (7,570 liters) of blood through the body every day.'],
    'what is the national animal of Russia': ['The national animal of Russia is the Russian bear.'],
    'who is the first human to reach the North Pole': ['The first human to reach the North Pole was Robert Peary.'],
    'tell me a famous art quote': ['"Art is the most intense mode of individualism that the world has known." - Oscar Wilde'],
    'what is the chemical symbol for neon': ['The chemical symbol for neon is Ne.'],
    'who painted "The Birth of Adam"': ['"The Birth of Adam" is part of Michelangelo\'s frescoes on the ceiling of the Sistine Chapel.'],
    'tell me a science fiction fact': ['The first science fiction novel is often considered to be "Frankenstein" by Mary Shelley, published in 1818.']
    

}

# Function to get a response based on user input
def get_response(user_input):
    user_input = user_input.lower()
    for pattern, responses in rules.items():
        if pattern in user_input:
            return random.choice(responses)
    return "I'm sorry, I don't understand."

# Main function for the chatbot
def chat():
    print("ChatBot: Hello! How can I assist you today? (Type 'exit' to end the conversation)")

    while True:
        user_input = input("You: ")

        if user_input.lower() == 'exit':
            print("ChatBot: Goodbye!")
            break

        response = get_response(user_input)
        print("ChatBot:", response)

# Run the chatbot
if __name__ == "__main__":
    chat()
